name: Commit Checks
on: [push]
jobs:
  prevent-fixup-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Prevent merging in fixup commits
      uses: 13rac1/block-fixup-merge-action@v1.1.1
