name: prevent-fixup-commits

on: [push]

jobs:
  build:
    name: ianwremmel/prevent-fixup-commits@v1.0.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ianwremmel/prevent-fixup-commits@v1.0.0
